### ISSUE TITLE
get same output for both match and mismatch

### ISSUE THREAD

**Issue by droe-nmdp** [Kingsford-Group/bloomtree#11]
[test3.txt](https://github.com/Kingsford-Group/bloomtree/files/450240/test3.txt)

The attached two test case returns the same output (different kmers) for the two queries, although I expect one to match and one not to match. Can you tell me what I'm doing wrong?

**Comment by Bradsol** [comment]
In this case it looks like the issue is simply a probability of failure. Remember that SBT's bloom filters are set to have about a 50% false positive rate for any given kmer [as the use case is typically a longer query consisting of many kmers]. The outcome is when you set the estimated number of kmers to 2, you really only allocate two bits of memory for the filter. It just so happens that in the hash generated to fit a filter of size 2, both ATATATA.... and TTTTT... seem to match to the same location.

Using the given code snippet I found that setting the size to 5, 10, and 100 all distinguish between those two queries while size 2 and 3 do not. However I guarantee two other queries of size 20 will give incorrect results at all of these sizes - it's simply the nature of a bloom filter that false positives will occur. You should never have ATATAT.... giving you a false response though.
